### ISSUE TITLE
gsh index and gsh goto do not appear with gsh help

### ISSUE THREAD

**Issue by julesChouquet** [phyver/GameShell#115]
After finishing the game, gsh intex and gsh goto are suggested by 'gsh goal' but not documented in 'gsh help'.
(P.S. The game is amazing, I think I will suggest it in a first grade OS class !)

**Comment by rlepigre** [comment]
Indeed, but I think that is on purpose, since we don't want these commands to be used when you play the game for the first time. As the goal message for the final mission suggests, you need to use `gsh HELP` (all capital letters) to see the full "help" message. The current version of that message is:
```

Congratulations!

You have finished all the missions.

You can now quit GameShell, or go back to some old missions.

Use ``gsh HELP`` to get a list of all GameShell commands.
The commands ``gsh index`` and ``gsh goto N`` are particularly 
interesting.

Note: the admin password has been changed to '$password'.

```

Do you find this message unclear? Or the choice we made confusing?

**Comment by julesChouquet** [comment]
Ok, I indeed missed the capital letter information, there is no issue at all, sorry (I assumed that 'help' would have a new behavior after the last mission, but I didn't read with enough attention…) !
