### ISSUE TITLE
Hosted GameShell in my blog

### ISSUE THREAD

**Issue by lucky-sideburn** [phyver/GameShell#135]
Hi!

I hosted GameShell in my blog. In the home page is link that points [here](https://ci.devopstribe.it/job/GameShell/build?delay=0sec). It is a job that create a private shell for anonymous users.

Wdyt? :D 

Thanks,
E

**Comment by Aierbote** [comment]
Hi! @lucky-sideburn 

First thing first, I'm a long time fan of this game but not a collaborator (_I don't know much of bash syntax sadly_ and I don't think I can dive into it anytime soon)

I was curious to check out your hosted version, even because it could be a nice way for me (macOS user) or for my friends (Windows users, in order to convert them to unix/Linux) to play a more recent version of the game.

But sadly I bump into this issue :

>  # 503 Service Unavailable 
> No server is available to handle this request.
