### ISSUE TITLE
Personalize the password and keep the French langague

### ISSUE THREAD

**Issue by sbnsec** [phyver/GameShell#150]
Hello everyone,

# Issue:

I’ve encountered a problem when trying to create customized game files `gameshell.sh` by using `archive.sh`, my goal is to change passwords of `gsh skip` and prevent cheating. 

When I use the `archive.sh` script to generate a new game file, the new version of GameShell only launches in English and no longer support French.

I suspect this might be due to a misunderstanding on my part regarding the documentation, but I haven’t been able to find a solution so far.

Is there a way to retain the French language when creating new game files using `archive.sh`?

# Context

I am an instructor at a computer science school, and I’ve been using the GameShell project as a learning platform to evaluate my students. I’ve integrated GameShell into a Docker environment to streamline the student evaluation process. Here’s an overview of how I’m using it and the modifications I’ve made:

## My Use of the Project:
- **Docker Environment with Supervisor and SSHD**: Students authenticate via SSH using a dedicated user. Upon login, the default shell runs a script (`start-new.sh`) that creates a directory for each student, copies the `gameshell.sh` file, and launches the game. 
- **Progress Tracking with Flask**: The supervisor also runs a Flask server that parses the game files to detect each student’s current level. A web page is accessible to all students, allowing them to track their progress in real time. The server uses the `-P passport` option to retrieve the player’s email and name.
- **Session Management**: Each student has their own dedicated game session, allowing for individual progress tracking.

I’d be happy to share these modifications with the community if you're interested.

## Steps to create the script : 

```
root@vm:~/GameShell# git pull
Déjà à jour.
root@vm:~/GameShell# ./utils/archive.sh -L fr -p dummy_password -P -a -t -z 
copying missions: ....................!...!.....!.............!....
removing unwanted languages
removing unnecessary files
setting admin password
setting default GameShell mode
creating archive
creating self-extracting archive
removing temporary directory

root@vm:~/GameShell# mkdir /home/user/test/
root@vm:~/GameShell# cp gameshell.sh /home/user/test/
root@vm:~/GameShell# chown -R user: /home/user/test/
root@vm:~/test#sudo -u user -s
root@vm:~/test# sudo -u user /home/user/test/gameshell.sh
Player's name:  ### The game is in english 
user@djme:/root/test$ locale
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES=fr_FR.UTF-8
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=


export LC_MESSAGES=fr_FR.UTF-8
user@vm:~/test$ ./gameshell.sh -L fr
Player's name: ### The game is in english 
```

How to create a portable, self contained, version of this challenge in french ? 

also the documentation spécifie : 

```
-k: keep the GameShell archive. The compressed tar archive is appended to a shell script to create the executable archive. With this option, you can keep the "standard" tar archive as well as the executable one.
```

https://github.com/phyver/GameShell/blob/master/doc/gameshell.md

but the option does not seems to exsist in archive.sh : 

```
./utils/archive.sh -h
archive.sh [OPTIONS] [MISSIONS]
create a GameShell standalone archive

options:
  -h              this message

  -p ...          choose password for admin commands
  -P              use the "passport mode" by default when running GameShell
  -A              use the "anonymous mode" by default when running GameShell
  -L LANGS        only keep the given languages (ex: -L 'en*,fr')
  -E              only keep english as a language, not generating any ".mo" file
                  and not using gettext

  -N ...          name of the archive / top directory (default: "gameshell")
  -I FILE         additional existing index file to include
                  (can be given several times)

  -S simple
  -S index
  -S overwrite
                  choose default savefile mode

  -a              keep 'auto.sh' scripts for missions that have one
  -t              keep 'test.sh' scripts for missions that have one
  -z              keep tgz archive

  -v              show the list of mission directories as they are being processed
```

Thanks,
Have a nice day,

**Comment by phyver** [comment]
Sorry for the delay...

Concerning the language problem, I'm not sure what happens. What system are you using?

- Just to make sure: is the locale `fr_FR.UTF-8` defined on your system? (On mine, it is called `fr_FR.utf8`.) You can check by looking for it in the output of `locale -a`.

- If you specify a language with `-L`, and the archive contains the appropriate language files, it *should* use this language.

- If you don't specify a language with the `-L` option, GameShell looks at the `LANGUAGE` environment variable, which is usually defined on GNU systems. (This is empty in your case.)

- Otherwise, the system should automatically use the `LC_MESSAGES` variable. In your case, it is defined. If the locale actually exists and the appropriate language files are included, it should make GameShell default to French.

Using the same commands you posted to generate the archive (with `fr_FR.utf8`, I do end up with a GameShell session in French. Can you check this really doesn't work for you? (There seem to be a problem with your sequence of commands, as the `sudo -u user -s` appears out of order...)

**Comment by phyver** [comment]
Oh, and about the `-k` option, the `gameshell.md` file is apparently wrong. The option to keep the archive is `-z`, as stated in the output of `archive.sh -h`.
I'll change that...

**Comment by sbnsec** [comment]
I think the problem is here : 

- If you specify a language with -L, and _the archive contains the appropriate language files_, it should use this language.

Maybe the French language is missing from the gameshell.sh, should I directly execute this script to play in French ? does I need to do something before starting the game ? 


Here the steps to generate an archive : 

```
user@gameshell:~/GameShell$ git status
Sur la branche master
Votre branche est à jour avec 'origin/master'.

rien à valider, la copie de travail est propre
user@gameshell:~/GameShell$ git pull
Déjà à jour.
user@gameshell:~/GameShell$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
user@gameshell:~/GameShell$ locale
locale     localectl  localedef  
user@gameshell:~/GameShell$ locale -a
C
C.utf8
en_US.utf8
fr_FR.utf8
POSIX
user@gameshell:~/GameShell$ locale
LANG=fr_FR.UTF-8
LANGUAGE=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=fr_FR.UTF-8
user@gameshell:~/GameShell$ ./utils/archive.sh -L fr -p dummy_password -P -a -t -z
copying missions: ....................!...!.....!.............!....
removing unwanted languages
removing unnecessary files
setting admin password
setting default GameShell mode
creating archive
creating self-extracting archive
removing temporary directory
```

Using the archive I just generated, and when I start it with `-L fr`, the game start in English : 

```
user@gameshell:~/GameShell$ ./gameshell.sh -L fr
Player's name: ^Cuser@gameshell:~/GameShell$ 
```

When I download the game directly from you're releases the game start in French : 

```
user@gameshell:~/GameShell$ wget https://github.com/phyver/GameShell/releases/download/v0.5.1/gameshell.sh -O gameshell-relase.sh
[...]
Sauvegarde en : « gameshell-relase.sh »
2024-11-04 11:47:42 (36,4 MB/s) — « gameshell-relase.sh » sauvegardé [201380/201380]

user@gameshell:~/GameShell$ bash gameshell-relase.sh -P 
Nom du joueur : ^Cuser@gameshell:~/GameShell$ 
```

Consequently, it seems that when I build the game, the French language is missing. 

Could you check on my steps followed if there's any issue, when I clone the project I'm on the `master` branch.

Thanks for fixing the doc. What is the consequences of creating an archive, what it's used for ? 


Thanks for your help.

**Comment by phyver** [comment]
Running the same steps on my machine works.

Can you give me the output of `locale` and `gsh env` from inside the GameShell session?


Can you try running the same commands, but with the locale `fr_FR.utf8`?
(It shouldn't make a difference, but  who knows?)
```
$ locale fr_FR.utf8
$ LANGUAGE=fr_FR.utf8
```

Can you also check that you do have `gettext` installed? GameShell sources the system file `gettext.sh` (usually found in `/usr/bin/gettext.sh`). If that doesn't work, everything will be in English:
```
$ source gettext.sh
$ eval_gettext
```
If you get a "command not found" for the second line, you might have to (re)install `gettext`.
(If you can get the archive from github to work in French, the problem shouldn't be there though.)



>What is the consequences of creating an archive, what it's used for ?
>
The `gameshell.sh` file is a shell script with a `.tgz` archive appended to it. The `-z` flag for `archive.sh` keeps this archive in the working directory instead of deleting it once the `gameshell.sh` file has been created.
You can extract the `gameshell.tgz` file and check that the french files are there: directory `gameshell/locale/fr/LC_MESSAGES/` should contain a bunch of `.mo` files.

By the way,you definitely don't need to use it to generate your final `gameshell.sh` file. :)
Similarly, you definitely don't need the `-t` flag ("keep the test files") and most probably don't need the `-a` flag ("keep the auto files").

**Comment by sbnsec** [comment]
Thanks you ! 

Apparently I was just missing a step, the system was missing some packages for the archive.sh to correctly works.

```
sudo apt install gettext man-db procps psmisc nano tree ncal x11-apps wget
```

It works perfectly.
