### ISSUE TITLE
Use $HOME/.bashrc instead of the ad hoc file `$GSH_ROOT/.bashrc/bashrc`

### ISSUE THREAD

**Issue by phyver** [phyver/GameShell#39]
Global configuration is stored in `$GSH_ROOT/.bashrc/bashrc`.
Having a real `$HOME/.bashrc` file (and `$HOME/.bash_profile`, or similar) would be cleaner, and we can then have a mission about configuring bash normally rather than in the chest.

It would also guarantee that running a new shell will keep the configuration.

The drawback is of course that `$HOME` is in the "world", and the player may see a strange file while exploring.

@rlepigre , what do you think?

**Comment by rlepigre** [comment]
I'm not sure I fully understand what you are proposing. Do you mean:
1. the "treasure" offering a `.bashrc` in the chest would be changed to have the `.bashrc` in `$HOME`,
2. or do you mean that you would put a `.bashrc` in `$HOME` from the start?

If it is 1, then I don't see anything wrong with that.
If it is 2, then I am a bit worried that this could be puzzling for the player.

**Comment by phyver** [comment]
I was proposing the second. (And the first as a consequence.)
My reasonning was that running `bash` from GameShell seems to take you "out" of GameShell, which is a little strange for a shell.
And I am also worried about puzzled player, but
  - no mission really takes place at the root of the world,
  - we can have a comment `# DO NOT MODIFY THE NEXT LINE` at the top of the file,
  - we can regenerate a correct `.bashrc` in `start.sh`, should it be missing.
  
The question is thus *do we risk puzzling a player who's never heard of `.bashrc`, or do we try running a shell "as standard" as possible?*

**Comment by rlepigre** [comment]
Why not define an alias for `bash` then? I think that should solve the "take you out of GameShell" problem. At least if the user does not run `/bin/bash`, but if they know how to do that I don't think we care.

I think I prefer to keep things as they are with the following changes:
- the fix I suggest above to prevent problems if the player runs `bash`,
- move the `.bashrc` given as treasure to `$HOME` so that it is in the standard location. We could even explain that this is a standard configuration file in a comment in the file.

What do you think?

**Comment by phyver** [comment]
You're right, I am probably splitting hair...
I like using `.bashrc` instead of `$GSH_CHEST/bashrc` though.
Let's change only that.
