### ISSUE TITLE
Check for unwanted output in the test script?

### ISSUE THREAD

**Issue by rlepigre** [phyver/GameShell#49]
I noticed that it often happens that there is unwanted output (typically error messages) that is introduced on `master`.
I'm wondering if we should try to check that there is no such output in our test script?

Not sure how to do that though. Can we rely on such messages to be shown on `stderr`?

**Comment by phyver** [comment]
> Not sure how to do that though. Can we rely on such messages to be shown on `stderr`?
>
Maybe?

At least for `make tests`, I'm pretty sure we expect some "normal" error messages to appear during the tests, so that wouldn't really solve it.

For `make check`, that could possibly work, but most of the time, those debug messages are precisely in some dark corner of the code that probably won't be triggered during `make check`.

A solution could be to define a `log` function that uses a special prefix like `>>GSH>>` to make it easy to find. It could also be made to send its output to `/dev/null` except in debug mode or when another variable `GSH_LOG` is defined.

That won't help for the messages that are still here though! :)
