### ISSUE TITLE
macOS - mission 29 got skipped

### ISSUE THREAD

**Issue by Aierbote** [phyver/GameShell#95]
First thing first. ___Mission 28 was hell___ XD
I'm pretty used to either `pgrep` + `pkill` and once I noticed I just let those imp spells multiply I've even tried `killall spell`

Back on topic:
```
Process names should be equal to the corresponding filename for mission processes/03_pstree_kill/deps.sh.
Error: mission 29 is cancelled because some dependencies are not met.
```
It would have been nice to see this `pstree` in action, even because I used `tree` even before it was introduced

**Comment by phyver** [comment]
It seems running `ps` or `pstree` on (most?) MacOS shows running scripts as

    $ ps
    ... sh script.sh

instead of

    $ ps
    ... script.sh

This means that depending on the arguments, they usually show as

    $ ps
    ... sh

which makes it impossible to differentiate between the different running scripts. When I believe that's the case, I skip the mission. :(
(That's the meaning of `Process names should be equal to the corresponding filename`.)

If that's indeed what happens, I don't know how to fix that!
